insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (1,'http://www.tucker-perez.org/', hip hop,to_date('2020/06/03', 'YYYY/MM/DD'),to_date('2020/07/24', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (2,'https://www.harvey.com/', blue-eyed soul,to_date('2021/10/23', 'YYYY/MM/DD'),to_date('2021/11/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (3,'https://www.pitts-christian.com/', salsa,to_date('2021/07/29', 'YYYY/MM/DD'),to_date('2021/09/03', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (4,'http://www.hays.com/', pop rock,to_date('2020/09/29', 'YYYY/MM/DD'),to_date('2020/11/27', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (5,'http://carter-castillo.com/', pop punk,to_date('2021/08/27', 'YYYY/MM/DD'),to_date('2021/09/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (6,'http://www.gomez-chavez.com/', southern gospel,to_date('2021/01/13', 'YYYY/MM/DD'),to_date('2021/01/25', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (7,'https://www.reeves.com/', breakbeat,to_date('2021/11/24', 'YYYY/MM/DD'),to_date('2022/02/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (8,'http://www.russo.com/', post-hardcore,to_date('2020/06/16', 'YYYY/MM/DD'),to_date('2020/09/07', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (9,'https://www.daniels.com/', new wave,to_date('2020/05/15', 'YYYY/MM/DD'),to_date('2020/06/27', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (10,'https://stanton.net/', breakcore,to_date('2020/04/11', 'YYYY/MM/DD'),to_date('2020/07/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (11,'https://taylor.com/', alternative rock,to_date('2020/06/20', 'YYYY/MM/DD'),to_date('2020/09/21', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (12,'http://www.carroll.com/', ccm,to_date('2022/03/27', 'YYYY/MM/DD'),to_date('2022/05/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (13,'https://www.brown-schmidt.net/', bachata,to_date('2020/03/01', 'YYYY/MM/DD'),to_date('2020/04/29', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (14,'https://curry-hamilton.com/', chanson,to_date('2020/01/09', 'YYYY/MM/DD'),to_date('2020/02/12', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (15,'http://roman.com/', quiet storm,to_date('2021/03/16', 'YYYY/MM/DD'),to_date('2021/05/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (16,'http://www.beck-ortiz.biz/', country rock,to_date('2020/08/04', 'YYYY/MM/DD'),to_date('2020/10/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (17,'https://kim.biz/', chill-out,to_date('2021/05/15', 'YYYY/MM/DD'),to_date('2021/06/27', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (18,'https://www.barajas-shaw.com/', qawwali,to_date('2022/03/18', 'YYYY/MM/DD'),to_date('2022/05/28', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (19,'https://www.hunter.info/', hard rock,to_date('2020/03/02', 'YYYY/MM/DD'),to_date('2020/04/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (20,'https://reese.com/', indietronica,to_date('2022/03/27', 'YYYY/MM/DD'),to_date('2022/06/12', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (21,'http://webb.net/', classic country,to_date('2020/02/13', 'YYYY/MM/DD'),to_date('2020/04/13', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (22,'https://shaw-barnes.info/', electric blues,to_date('2021/08/25', 'YYYY/MM/DD'),to_date('2021/12/03', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (23,'http://www.ward-williams.com/', uk garage,to_date('2020/05/30', 'YYYY/MM/DD'),to_date('2020/06/24', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (24,'http://cruz-taylor.org/', math-core,to_date('2021/05/31', 'YYYY/MM/DD'),to_date('2021/07/21', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (25,'http://walters.org/', pop rock,to_date('2020/03/04', 'YYYY/MM/DD'),to_date('2020/05/07', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (26,'https://www.fuller.info/', post-grunge,to_date('2020/11/15', 'YYYY/MM/DD'),to_date('2021/02/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (27,'https://www.salas.com/', breakcore,to_date('2021/05/17', 'YYYY/MM/DD'),to_date('2021/07/02', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (28,'https://www.foster.info/', filk,to_date('2020/01/16', 'YYYY/MM/DD'),to_date('2020/03/07', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (29,'https://www.smith.info/', latin jazz,to_date('2020/01/10', 'YYYY/MM/DD'),to_date('2020/02/17', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (30,'https://www.evans.com/', jump blues,to_date('2021/01/28', 'YYYY/MM/DD'),to_date('2021/04/01', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (31,'https://www.abbott-clarke.com/', soul jazz,to_date('2021/11/15', 'YYYY/MM/DD'),to_date('2021/12/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (32,'http://mitchell.biz/', disco,to_date('2020/10/21', 'YYYY/MM/DD'),to_date('2021/01/06', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (33,'http://www.reyes.com/', doo-wop,to_date('2021/11/20', 'YYYY/MM/DD'),to_date('2021/12/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (34,'http://lopez.net/', classic country,to_date('2021/06/26', 'YYYY/MM/DD'),to_date('2021/09/11', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (35,'http://www.hernandez-smith.com/', rap,to_date('2020/03/08', 'YYYY/MM/DD'),to_date('2020/06/13', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (36,'http://jenkins-luna.biz/', charanga,to_date('2021/02/06', 'YYYY/MM/DD'),to_date('2021/04/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (37,'https://golden.com/', noise rock,to_date('2022/03/25', 'YYYY/MM/DD'),to_date('2022/04/17', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (38,'https://wood.com/', dance pop,to_date('2021/07/31', 'YYYY/MM/DD'),to_date('2021/10/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (39,'https://www.davis-howard.com/', orchestra,to_date('2021/02/14', 'YYYY/MM/DD'),to_date('2021/05/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (40,'http://www.mason.com/', cool jazz,to_date('2021/01/04', 'YYYY/MM/DD'),to_date('2021/03/02', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (41,'http://carpenter.com/', gothic metal,to_date('2020/05/13', 'YYYY/MM/DD'),to_date('2020/08/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (42,'https://www.hill-hoffman.biz/', ska punk,to_date('2021/11/28', 'YYYY/MM/DD'),to_date('2021/12/29', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (43,'https://zamora.info/', blues,to_date('2021/10/06', 'YYYY/MM/DD'),to_date('2021/12/06', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (44,'https://nelson.com/', salsa,to_date('2022/01/20', 'YYYY/MM/DD'),to_date('2022/04/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (45,'https://moore-green.com/', modern rock,to_date('2021/05/25', 'YYYY/MM/DD'),to_date('2021/06/25', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (46,'http://www.martin.com/', delta blues,to_date('2021/06/06', 'YYYY/MM/DD'),to_date('2021/06/18', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (47,'https://www.ryan-price.com/', texas blues,to_date('2020/11/21', 'YYYY/MM/DD'),to_date('2021/02/21', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (48,'https://atkins.biz/', blues,to_date('2021/07/18', 'YYYY/MM/DD'),to_date('2021/08/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (49,'http://www.willis.org/', trip hop,to_date('2022/01/31', 'YYYY/MM/DD'),to_date('2022/05/01', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (50,'https://www.burnett-duffy.biz/', hardcore techno,to_date('2021/12/12', 'YYYY/MM/DD'),to_date('2022/01/18', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (51,'https://burnett.com/', glam rock,to_date('2021/05/29', 'YYYY/MM/DD'),to_date('2021/08/16', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (52,'https://berry-cook.info/', brazilian jazz,to_date('2020/09/05', 'YYYY/MM/DD'),to_date('2020/11/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (53,'https://www.wolf.com/', gangster rap,to_date('2021/08/14', 'YYYY/MM/DD'),to_date('2021/09/12', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (54,'https://manning-ramos.org/', rock,to_date('2021/04/03', 'YYYY/MM/DD'),to_date('2021/05/03', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (55,'https://www.hickman.com/', brazilian jazz,to_date('2020/07/16', 'YYYY/MM/DD'),to_date('2020/10/02', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (56,'http://stephens.net/', soft rock,to_date('2021/09/03', 'YYYY/MM/DD'),to_date('2021/10/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (57,'http://luna.com/', easy listening,to_date('2022/03/20', 'YYYY/MM/DD'),to_date('2022/06/28', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (58,'https://duncan.biz/', dance rock,to_date('2020/05/28', 'YYYY/MM/DD'),to_date('2020/08/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (59,'https://harvey.com/', singer-songwriter,to_date('2021/02/02', 'YYYY/MM/DD'),to_date('2021/03/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (60,'http://www.roberson.com/', experimental rock,to_date('2020/10/03', 'YYYY/MM/DD'),to_date('2020/10/17', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (61,'http://www.bryant.com/', meditation,to_date('2021/06/10', 'YYYY/MM/DD'),to_date('2021/09/18', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (62,'http://www.ortiz-morales.net/', ccm,to_date('2021/02/03', 'YYYY/MM/DD'),to_date('2021/02/16', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (63,'http://guerra.com/', speedcore,to_date('2020/07/19', 'YYYY/MM/DD'),to_date('2020/09/27', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (64,'http://www.morrison.com/', southern rock,to_date('2021/04/02', 'YYYY/MM/DD'),to_date('2021/05/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (65,'http://gutierrez-bright.com/', zouk,to_date('2021/11/07', 'YYYY/MM/DD'),to_date('2021/12/24', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (66,'https://www.hanson.org/', trance,to_date('2021/10/28', 'YYYY/MM/DD'),to_date('2021/12/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (67,'http://www.brock-trevino.com/', punk,to_date('2020/12/04', 'YYYY/MM/DD'),to_date('2021/01/16', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (68,'http://stephenson-guzman.com/', suomi rock,to_date('2021/08/27', 'YYYY/MM/DD'),to_date('2021/10/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (69,'https://www.edwards.com/', rock,to_date('2021/06/09', 'YYYY/MM/DD'),to_date('2021/07/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (70,'http://brooks.net/', easy listening,to_date('2021/04/04', 'YYYY/MM/DD'),to_date('2021/06/30', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (71,'http://lopez.org/', gabba,to_date('2021/03/25', 'YYYY/MM/DD'),to_date('2021/04/29', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (72,'http://www.murphy.net/', ccm,to_date('2021/10/18', 'YYYY/MM/DD'),to_date('2022/01/21', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (73,'https://www.garcia-donovan.com/', pop rap,to_date('2020/05/11', 'YYYY/MM/DD'),to_date('2020/07/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (74,'http://jacobs-medina.org/', heavy metal,to_date('2020/12/20', 'YYYY/MM/DD'),to_date('2021/02/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (75,'https://campbell-tucker.com/', hip hop,to_date('2021/06/30', 'YYYY/MM/DD'),to_date('2021/09/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (76,'https://www.peterson.info/', industrial metal,to_date('2021/08/24', 'YYYY/MM/DD'),to_date('2021/11/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (77,'http://sanford.net/', rock,to_date('2020/02/21', 'YYYY/MM/DD'),to_date('2020/03/27', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (78,'http://www.smith.net/', freestyle,to_date('2021/12/29', 'YYYY/MM/DD'),to_date('2022/03/03', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (79,'http://johnson.biz/', brill building pop,to_date('2020/02/11', 'YYYY/MM/DD'),to_date('2020/04/29', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (80,'https://jackson.biz/', melodic hardcore,to_date('2021/11/11', 'YYYY/MM/DD'),to_date('2021/12/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (81,'https://davis.com/', british pop,to_date('2020/08/04', 'YYYY/MM/DD'),to_date('2020/09/16', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (82,'http://washington.com/', heavy metal,to_date('2020/11/15', 'YYYY/MM/DD'),to_date('2021/01/06', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (83,'https://reyes.net/', chanson,to_date('2021/01/15', 'YYYY/MM/DD'),to_date('2021/03/11', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (84,'http://anderson.org/', country rock,to_date('2020/10/11', 'YYYY/MM/DD'),to_date('2021/01/11', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (85,'http://wells.com/', country rock,to_date('2021/05/07', 'YYYY/MM/DD'),to_date('2021/08/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (86,'http://www.medina.com/', folk-pop,to_date('2020/06/07', 'YYYY/MM/DD'),to_date('2020/08/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (87,'https://www.lewis-alvarez.info/', easy listening,to_date('2020/08/20', 'YYYY/MM/DD'),to_date('2020/09/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (88,'https://martinez-waller.org/', stoner metal,to_date('2020/09/22', 'YYYY/MM/DD'),to_date('2020/10/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (89,'http://higgins.com/', western swing,to_date('2020/09/07', 'YYYY/MM/DD'),to_date('2020/12/01', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (90,'http://www.baker.com/', indie rock,to_date('2020/08/16', 'YYYY/MM/DD'),to_date('2020/10/05', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (91,'http://www.gomez.com/', rap rock,to_date('2020/01/11', 'YYYY/MM/DD'),to_date('2020/01/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (92,'http://www.turner.info/', indie rock,to_date('2021/06/02', 'YYYY/MM/DD'),to_date('2021/07/07', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (93,'http://www.howard.info/', ranchera,to_date('2020/12/23', 'YYYY/MM/DD'),to_date('2021/01/28', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (94,'http://phillips.com/', chanson,to_date('2020/08/12', 'YYYY/MM/DD'),to_date('2020/10/15', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (95,'https://bush-harris.com/', hip hop,to_date('2021/04/14', 'YYYY/MM/DD'),to_date('2021/07/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (96,'https://www.woods-ballard.net/', german pop,to_date('2020/09/09', 'YYYY/MM/DD'),to_date('2020/11/06', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (97,'http://www.garza.com/', easy listening,to_date('2021/11/24', 'YYYY/MM/DD'),to_date('2022/02/24', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (98,'https://www.suarez.org/', breakcore,to_date('2022/01/03', 'YYYY/MM/DD'),to_date('2022/04/05', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (99,'https://burnett-dominguez.net/', hard bop,to_date('2020/06/19', 'YYYY/MM/DD'),to_date('2020/08/29', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (100,'http://www.campbell.com/', free jazz,to_date('2021/07/30', 'YYYY/MM/DD'),to_date('2021/10/29', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (101,'http://mccullough-smith.com/', shoegaze,to_date('2020/10/22', 'YYYY/MM/DD'),to_date('2021/01/29', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (102,'http://brown-bryant.net/', chill-out,to_date('2020/09/17', 'YYYY/MM/DD'),to_date('2020/10/26', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (103,'https://www.franklin-baker.com/', gospel,to_date('2021/12/18', 'YYYY/MM/DD'),to_date('2022/01/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (104,'https://www.myers-bowen.com/', blues-rock,to_date('2021/01/25', 'YYYY/MM/DD'),to_date('2021/03/17', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (105,'http://www.harris-decker.com/', latin jazz,to_date('2020/08/09', 'YYYY/MM/DD'),to_date('2020/11/11', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (106,'http://powell.com/', chanson,to_date('2020/05/16', 'YYYY/MM/DD'),to_date('2020/06/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (107,'https://www.brown.org/', tech house,to_date('2020/08/06', 'YYYY/MM/DD'),to_date('2020/11/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (108,'https://www.stevens-mckinney.net/', hip hop,to_date('2022/02/12', 'YYYY/MM/DD'),to_date('2022/04/06', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (109,'https://www.miller.net/', country,to_date('2022/03/29', 'YYYY/MM/DD'),to_date('2022/07/07', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (110,'https://hughes-flowers.com/', roots reggae,to_date('2020/01/08', 'YYYY/MM/DD'),to_date('2020/01/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (111,'http://giles.com/', freakbeat,to_date('2021/11/12', 'YYYY/MM/DD'),to_date('2022/01/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (112,'https://www.reyes.com/', chicago soul,to_date('2021/12/19', 'YYYY/MM/DD'),to_date('2022/02/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (113,'https://bridges-washington.com/', blues-rock,to_date('2020/05/04', 'YYYY/MM/DD'),to_date('2020/06/28', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (114,'https://porter-perez.com/', jazz fusion,to_date('2021/09/26', 'YYYY/MM/DD'),to_date('2021/10/24', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (115,'http://www.allen.com/', delta blues,to_date('2022/02/09', 'YYYY/MM/DD'),to_date('2022/04/17', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (116,'http://www.gordon.com/', new jack swing,to_date('2020/10/31', 'YYYY/MM/DD'),to_date('2020/11/12', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (117,'https://www.cherry.org/', piedmont blues,to_date('2021/09/30', 'YYYY/MM/DD'),to_date('2021/10/26', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (118,'https://lee.info/', jazz funk,to_date('2021/08/23', 'YYYY/MM/DD'),to_date('2021/10/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (119,'http://grant-davis.net/', male vocalist,to_date('2020/02/03', 'YYYY/MM/DD'),to_date('2020/04/29', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (120,'http://www.monroe-clark.com/', chanson,to_date('2021/03/28', 'YYYY/MM/DD'),to_date('2021/06/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (121,'http://munoz.com/', ghetto tech,to_date('2020/02/26', 'YYYY/MM/DD'),to_date('2020/04/26', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (122,'http://ross.net/', dance pop,to_date('2021/04/22', 'YYYY/MM/DD'),to_date('2021/06/24', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (123,'http://www.santiago.net/', country rock,to_date('2020/04/25', 'YYYY/MM/DD'),to_date('2020/06/24', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (124,'http://www.lee-king.com/', stoner metal,to_date('2020/04/17', 'YYYY/MM/DD'),to_date('2020/05/25', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (125,'http://www.wagner.com/', singer-songwriter,to_date('2022/01/25', 'YYYY/MM/DD'),to_date('2022/04/06', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (126,'https://www.fields.com/', blues-rock,to_date('2021/06/04', 'YYYY/MM/DD'),to_date('2021/09/07', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (127,'https://cook.biz/', guitar,to_date('2020/04/05', 'YYYY/MM/DD'),to_date('2020/04/16', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (128,'http://gilmore.com/', pop rap,to_date('2020/11/12', 'YYYY/MM/DD'),to_date('2020/12/01', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (129,'http://dudley.com/', progressive house,to_date('2021/12/26', 'YYYY/MM/DD'),to_date('2022/02/28', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (130,'http://thomas.com/', hip hop,to_date('2020/04/09', 'YYYY/MM/DD'),to_date('2020/05/15', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (131,'http://www.james-dyer.org/', post-grunge,to_date('2021/03/04', 'YYYY/MM/DD'),to_date('2021/05/13', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (132,'https://www.mccullough.com/', singer-songwriter,to_date('2020/11/07', 'YYYY/MM/DD'),to_date('2021/01/05', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (133,'http://www.archer.net/', gospel,to_date('2020/03/01', 'YYYY/MM/DD'),to_date('2020/06/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (134,'https://larson.com/', blue-eyed soul,to_date('2021/11/15', 'YYYY/MM/DD'),to_date('2022/01/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (135,'https://west-harrison.com/', latin jazz,to_date('2020/06/13', 'YYYY/MM/DD'),to_date('2020/07/26', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (136,'https://gonzalez-thompson.biz/', vocal house,to_date('2020/10/08', 'YYYY/MM/DD'),to_date('2020/12/28', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (137,'http://fischer.com/', los angeles,to_date('2021/06/19', 'YYYY/MM/DD'),to_date('2021/08/25', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (138,'https://smith.info/', lovers rock,to_date('2021/07/14', 'YYYY/MM/DD'),to_date('2021/10/16', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (139,'http://www.rose-williams.com/', experimental rock,to_date('2022/01/25', 'YYYY/MM/DD'),to_date('2022/04/11', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (140,'https://www.howard.net/', arabesque,to_date('2020/10/17', 'YYYY/MM/DD'),to_date('2020/11/19', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (141,'https://bailey.info/', grunge,to_date('2020/02/03', 'YYYY/MM/DD'),to_date('2020/02/29', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (142,'https://johnson.com/', dance pop,to_date('2021/12/28', 'YYYY/MM/DD'),to_date('2022/03/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (143,'https://brown-gibson.com/', rock,to_date('2021/10/13', 'YYYY/MM/DD'),to_date('2021/11/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (144,'https://www.castillo.com/', blues-rock,to_date('2020/04/21', 'YYYY/MM/DD'),to_date('2020/05/13', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (145,'http://www.wang.com/', bossa nova,to_date('2021/05/15', 'YYYY/MM/DD'),to_date('2021/08/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (146,'http://frazier.com/', zouk,to_date('2020/03/21', 'YYYY/MM/DD'),to_date('2020/05/03', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (147,'http://www.hansen.info/', rock,to_date('2020/10/04', 'YYYY/MM/DD'),to_date('2020/10/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (148,'https://www.taylor.com/', thrash core,to_date('2021/09/30', 'YYYY/MM/DD'),to_date('2021/12/15', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (149,'http://jones.com/', folk-pop,to_date('2020/07/04', 'YYYY/MM/DD'),to_date('2020/09/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (150,'http://www.bentley-zamora.info/', ccm,to_date('2022/02/11', 'YYYY/MM/DD'),to_date('2022/03/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (151,'http://moore-hamilton.com/', breakcore,to_date('2022/03/07', 'YYYY/MM/DD'),to_date('2022/05/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (152,'https://flores-bryant.net/', dance pop,to_date('2020/09/20', 'YYYY/MM/DD'),to_date('2020/11/03', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (153,'http://johnson-lawrence.com/', easy listening,to_date('2021/04/15', 'YYYY/MM/DD'),to_date('2021/06/17', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (154,'https://www.king.info/', tech house,to_date('2020/12/07', 'YYYY/MM/DD'),to_date('2021/03/17', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (155,'https://www.dyer.com/', frevo,to_date('2021/04/16', 'YYYY/MM/DD'),to_date('2021/07/07', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (156,'http://johnston.com/', black metal,to_date('2022/02/04', 'YYYY/MM/DD'),to_date('2022/02/15', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (157,'http://perez-riddle.net/', meditation,to_date('2020/09/30', 'YYYY/MM/DD'),to_date('2020/12/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (158,'https://www.hernandez.com/', serialism,to_date('2020/11/22', 'YYYY/MM/DD'),to_date('2021/01/31', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (159,'https://dodson.com/', roots reggae,to_date('2021/07/11', 'YYYY/MM/DD'),to_date('2021/09/19', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (160,'https://adams.com/', bluegrass,to_date('2022/03/27', 'YYYY/MM/DD'),to_date('2022/05/21', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (161,'http://www.ryan.info/', jazz funk,to_date('2021/05/31', 'YYYY/MM/DD'),to_date('2021/09/05', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (162,'https://wagner.com/', grunge,to_date('2022/01/17', 'YYYY/MM/DD'),to_date('2022/02/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (163,'https://www.duncan.org/', vocal jazz,to_date('2021/02/26', 'YYYY/MM/DD'),to_date('2021/04/02', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (164,'http://johnson.com/', alternative metal,to_date('2021/06/05', 'YYYY/MM/DD'),to_date('2021/07/29', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (165,'http://www.lopez-hardy.com/', flamenco,to_date('2020/06/06', 'YYYY/MM/DD'),to_date('2020/07/07', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (166,'https://www.mason-jones.com/', blues-rock,to_date('2021/08/24', 'YYYY/MM/DD'),to_date('2021/11/25', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (167,'http://www.martinez.com/', gangster rap,to_date('2020/04/12', 'YYYY/MM/DD'),to_date('2020/06/05', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (168,'http://www.anderson-king.info/', honky tonk,to_date('2021/02/01', 'YYYY/MM/DD'),to_date('2021/03/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (169,'https://www.wilkinson.biz/', electronica,to_date('2020/03/01', 'YYYY/MM/DD'),to_date('2020/05/05', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (170,'https://www.sanchez.info/', vocal house,to_date('2021/12/12', 'YYYY/MM/DD'),to_date('2022/03/17', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (171,'https://benton.com/', country gospel,to_date('2020/01/13', 'YYYY/MM/DD'),to_date('2020/03/15', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (172,'http://www.campos.com/', hardcore punk,to_date('2021/12/28', 'YYYY/MM/DD'),to_date('2022/03/21', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (173,'http://www.park.info/', heavy metal,to_date('2021/06/08', 'YYYY/MM/DD'),to_date('2021/07/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (174,'https://www.gonzalez.com/', post-grunge,to_date('2021/11/08', 'YYYY/MM/DD'),to_date('2022/01/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (175,'https://stephens.com/', brill building pop,to_date('2020/12/03', 'YYYY/MM/DD'),to_date('2021/01/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (176,'https://mendoza.biz/', easy listening,to_date('2021/11/18', 'YYYY/MM/DD'),to_date('2022/01/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (177,'http://www.reed-santos.info/', tejano,to_date('2021/05/07', 'YYYY/MM/DD'),to_date('2021/06/30', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (178,'https://klein.info/', pop rock,to_date('2020/06/25', 'YYYY/MM/DD'),to_date('2020/09/07', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (179,'http://www.cox-gates.com/', chill-out,to_date('2020/04/10', 'YYYY/MM/DD'),to_date('2020/05/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (180,'https://small-heath.com/', sympho black metal,to_date('2021/10/20', 'YYYY/MM/DD'),to_date('2022/01/15', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (181,'https://nichols.net/', chamber jazz,to_date('2021/09/28', 'YYYY/MM/DD'),to_date('2021/11/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (182,'https://www.gray-alvarez.info/', dancehall,to_date('2021/08/23', 'YYYY/MM/DD'),to_date('2021/10/26', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (183,'https://spence.info/', hard house,to_date('2021/02/03', 'YYYY/MM/DD'),to_date('2021/04/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (184,'http://collins.info/', rap,to_date('2021/01/04', 'YYYY/MM/DD'),to_date('2021/02/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (185,'http://www.may.org/', industrial metal,to_date('2021/09/23', 'YYYY/MM/DD'),to_date('2021/11/02', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (186,'https://mclean.com/', gaita,to_date('2022/04/03', 'YYYY/MM/DD'),to_date('2022/05/26', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (187,'http://hines.org/', honky tonk,to_date('2020/03/22', 'YYYY/MM/DD'),to_date('2020/06/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (188,'https://www.powell.com/', grime,to_date('2021/11/12', 'YYYY/MM/DD'),to_date('2021/12/30', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (189,'https://stanley.org/', new romantic,to_date('2021/09/10', 'YYYY/MM/DD'),to_date('2021/12/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (190,'https://www.hensley.net/', happy hardcore,to_date('2021/10/28', 'YYYY/MM/DD'),to_date('2022/01/28', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (191,'https://www.sanchez.com/', tech house,to_date('2020/11/23', 'YYYY/MM/DD'),to_date('2020/12/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (192,'https://moore.org/', texas blues,to_date('2021/08/19', 'YYYY/MM/DD'),to_date('2021/09/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (193,'http://white.com/', modern rock,to_date('2020/03/19', 'YYYY/MM/DD'),to_date('2020/04/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (194,'https://www.taylor.net/', brazil,to_date('2020/04/11', 'YYYY/MM/DD'),to_date('2020/06/16', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (195,'https://huber.info/', future jazz,to_date('2022/03/25', 'YYYY/MM/DD'),to_date('2022/05/19', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (196,'http://hughes-gordon.info/', bossa nova,to_date('2021/01/07', 'YYYY/MM/DD'),to_date('2021/03/21', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (197,'http://www.miranda.com/', breakbeat,to_date('2020/11/13', 'YYYY/MM/DD'),to_date('2021/01/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (198,'https://powell.net/', black metal,to_date('2020/04/28', 'YYYY/MM/DD'),to_date('2020/07/18', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (199,'http://www.harper.biz/', dance rock,to_date('2020/02/03', 'YYYY/MM/DD'),to_date('2020/04/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (200,'https://foster.org/', blues-rock,to_date('2020/02/24', 'YYYY/MM/DD'),to_date('2020/03/30', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (201,'https://www.williams.com/', french pop,to_date('2020/12/06', 'YYYY/MM/DD'),to_date('2021/01/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (202,'https://green-stewart.info/', dance rock,to_date('2021/06/24', 'YYYY/MM/DD'),to_date('2021/09/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (203,'https://www.harrison.org/', greek,to_date('2021/04/07', 'YYYY/MM/DD'),to_date('2021/06/17', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (204,'https://ellis.info/', punk,to_date('2021/04/02', 'YYYY/MM/DD'),to_date('2021/06/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (205,'https://www.cunningham-soto.com/', r&b,to_date('2021/08/23', 'YYYY/MM/DD'),to_date('2021/10/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (206,'https://www.castaneda.net/', breakbeat,to_date('2020/03/24', 'YYYY/MM/DD'),to_date('2020/06/12', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (207,'https://www.garcia.org/', opera,to_date('2022/03/10', 'YYYY/MM/DD'),to_date('2022/05/12', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (208,'http://www.miller.com/', folk-pop,to_date('2020/04/07', 'YYYY/MM/DD'),to_date('2020/05/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (209,'https://bonilla.info/', ska,to_date('2021/11/29', 'YYYY/MM/DD'),to_date('2022/01/28', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (210,'https://www.powers.com/', british invasion,to_date('2020/08/23', 'YYYY/MM/DD'),to_date('2020/11/17', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (211,'http://powers.net/', turnablism,to_date('2021/12/20', 'YYYY/MM/DD'),to_date('2022/03/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (212,'http://www.riley.info/', pop folk,to_date('2020/08/12', 'YYYY/MM/DD'),to_date('2020/09/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (213,'http://wilson-newton.com/', jazz fusion,to_date('2020/04/20', 'YYYY/MM/DD'),to_date('2020/06/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (214,'http://fisher.info/', alternative hip hop,to_date('2020/07/30', 'YYYY/MM/DD'),to_date('2020/09/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (215,'https://pierce-case.com/', chicago blues,to_date('2021/09/30', 'YYYY/MM/DD'),to_date('2021/10/18', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (216,'http://www.lee.com/', latin jazz,to_date('2020/09/24', 'YYYY/MM/DD'),to_date('2020/12/11', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (217,'http://www.jones-burton.com/', breakbeat,to_date('2021/10/16', 'YYYY/MM/DD'),to_date('2021/11/26', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (218,'http://douglas.net/', stoner metal,to_date('2021/08/14', 'YYYY/MM/DD'),to_date('2021/10/23', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (219,'https://www.hunt.com/', blues-rock,to_date('2021/02/16', 'YYYY/MM/DD'),to_date('2021/04/18', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (220,'http://stewart.org/', western swing,to_date('2022/01/31', 'YYYY/MM/DD'),to_date('2022/04/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (221,'http://hunt.com/', latin jazz,to_date('2020/03/26', 'YYYY/MM/DD'),to_date('2020/04/06', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (222,'http://brady-mckay.com/', doom metal,to_date('2021/04/20', 'YYYY/MM/DD'),to_date('2021/05/06', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (223,'https://ortiz-roberts.biz/', hard house,to_date('2021/08/07', 'YYYY/MM/DD'),to_date('2021/10/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (224,'https://johnson-hubbard.com/', world beat,to_date('2020/04/27', 'YYYY/MM/DD'),to_date('2020/07/03', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (225,'https://brown.info/', twee pop,to_date('2020/06/19', 'YYYY/MM/DD'),to_date('2020/08/31', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (226,'http://garcia.info/', rock,to_date('2021/02/01', 'YYYY/MM/DD'),to_date('2021/02/24', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (227,'https://liu.biz/', teen pop,to_date('2020/05/26', 'YYYY/MM/DD'),to_date('2020/07/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (228,'https://burton-johns.com/', doom metal,to_date('2020/08/21', 'YYYY/MM/DD'),to_date('2020/10/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (229,'http://www.spears.com/', smooth jazz,to_date('2020/05/16', 'YYYY/MM/DD'),to_date('2020/07/29', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (230,'http://logan-griffin.com/', power pop,to_date('2021/09/05', 'YYYY/MM/DD'),to_date('2021/11/11', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (231,'http://www.thomas.org/', latin pop,to_date('2020/02/19', 'YYYY/MM/DD'),to_date('2020/04/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (232,'https://www.hardy.net/', techno,to_date('2020/12/15', 'YYYY/MM/DD'),to_date('2021/01/29', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (233,'http://www.myers.com/', gangster rap,to_date('2020/03/07', 'YYYY/MM/DD'),to_date('2020/03/19', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (234,'http://williams-romero.com/', viking metal,to_date('2022/03/18', 'YYYY/MM/DD'),to_date('2022/06/02', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (235,'https://simmons-strong.info/', gangster rap,to_date('2020/04/26', 'YYYY/MM/DD'),to_date('2020/07/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (236,'https://www.lang-myers.com/', rap metal,to_date('2021/03/25', 'YYYY/MM/DD'),to_date('2021/06/03', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (237,'https://brown.com/', chicago blues,to_date('2021/04/27', 'YYYY/MM/DD'),to_date('2021/06/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (238,'https://www.davis.com/', hardcore punk,to_date('2021/01/16', 'YYYY/MM/DD'),to_date('2021/03/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (239,'https://www.greene-rivera.com/', gabba,to_date('2020/12/12', 'YYYY/MM/DD'),to_date('2021/03/17', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (240,'http://www.benitez-woodard.biz/', rap metal,to_date('2020/04/26', 'YYYY/MM/DD'),to_date('2020/05/25', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (241,'https://hurley.com/', requiem,to_date('2021/09/14', 'YYYY/MM/DD'),to_date('2021/10/23', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (242,'https://daniels-hernandez.biz/', europop,to_date('2021/08/17', 'YYYY/MM/DD'),to_date('2021/11/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (243,'http://ruiz-hodges.com/', rock,to_date('2021/01/17', 'YYYY/MM/DD'),to_date('2021/03/24', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (244,'https://mckee.com/', post-grunge,to_date('2020/04/22', 'YYYY/MM/DD'),to_date('2020/07/19', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (245,'https://www.williams-davis.info/', alternative metal,to_date('2021/06/19', 'YYYY/MM/DD'),to_date('2021/08/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (246,'https://miller-long.com/', gabba,to_date('2020/10/30', 'YYYY/MM/DD'),to_date('2021/01/25', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (247,'https://www.brown.com/', irish folk,to_date('2020/12/28', 'YYYY/MM/DD'),to_date('2021/02/06', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (248,'http://www.day.com/', dance rock,to_date('2020/06/26', 'YYYY/MM/DD'),to_date('2020/08/28', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (249,'http://www.frank-ramos.net/', soul jazz,to_date('2021/06/26', 'YYYY/MM/DD'),to_date('2021/08/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (250,'http://butler.org/', rap metal,to_date('2020/08/28', 'YYYY/MM/DD'),to_date('2020/11/01', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (251,'https://montgomery.com/', country blues,to_date('2022/03/15', 'YYYY/MM/DD'),to_date('2022/04/21', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (252,'https://white.biz/', instrumental pop,to_date('2020/07/17', 'YYYY/MM/DD'),to_date('2020/08/19', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (253,'http://www.phillips-pitts.org/', funk metal,to_date('2021/02/24', 'YYYY/MM/DD'),to_date('2021/04/24', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (254,'http://boyd.com/', soundtrack,to_date('2021/06/16', 'YYYY/MM/DD'),to_date('2021/07/25', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (255,'http://lucero-brown.net/', rap,to_date('2022/02/25', 'YYYY/MM/DD'),to_date('2022/04/26', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (256,'http://www.jones.com/', chicago soul,to_date('2020/12/11', 'YYYY/MM/DD'),to_date('2020/12/30', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (257,'https://www.smith-mcclure.com/', chanson,to_date('2021/08/10', 'YYYY/MM/DD'),to_date('2021/09/16', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (258,'https://www.lambert.com/', gabba,to_date('2020/04/26', 'YYYY/MM/DD'),to_date('2020/07/18', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (259,'http://www.pierce.net/', british pop,to_date('2021/02/08', 'YYYY/MM/DD'),to_date('2021/05/07', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (260,'https://le.biz/', pop rock,to_date('2020/05/30', 'YYYY/MM/DD'),to_date('2020/07/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (261,'http://marshall.com/', big beat,to_date('2021/08/17', 'YYYY/MM/DD'),to_date('2021/09/03', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (262,'http://carter.com/', roots reggae,to_date('2020/10/02', 'YYYY/MM/DD'),to_date('2020/10/12', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (263,'http://www.sherman-bowman.com/', rock,to_date('2021/06/14', 'YYYY/MM/DD'),to_date('2021/06/24', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (264,'http://wilson-chan.net/', trip hop,to_date('2021/09/02', 'YYYY/MM/DD'),to_date('2021/10/25', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (265,'https://www.cannon.com/', hard rock,to_date('2020/01/09', 'YYYY/MM/DD'),to_date('2020/03/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (266,'http://www.miranda-farmer.com/', progressive house,to_date('2020/08/14', 'YYYY/MM/DD'),to_date('2020/09/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (267,'https://www.barnett-wood.com/', roots reggae,to_date('2020/08/19', 'YYYY/MM/DD'),to_date('2020/09/16', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (268,'http://barnes-obrien.org/', classic country,to_date('2021/02/24', 'YYYY/MM/DD'),to_date('2021/05/26', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (269,'http://robles.com/', gabba,to_date('2020/11/15', 'YYYY/MM/DD'),to_date('2020/12/15', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (270,'https://mccall.info/', hip hop,to_date('2021/12/21', 'YYYY/MM/DD'),to_date('2022/01/31', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (271,'http://www.cooke.com/', hip hop,to_date('2020/07/29', 'YYYY/MM/DD'),to_date('2020/10/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (272,'https://www.evans.biz/', orchestra,to_date('2020/06/14', 'YYYY/MM/DD'),to_date('2020/08/26', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (273,'http://www.robinson-lucas.com/', honky tonk,to_date('2021/07/20', 'YYYY/MM/DD'),to_date('2021/09/13', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (274,'http://www.parks.org/', hip hop,to_date('2022/03/16', 'YYYY/MM/DD'),to_date('2022/04/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (275,'https://barnes.com/', sympho black metal,to_date('2020/10/24', 'YYYY/MM/DD'),to_date('2021/01/01', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (276,'https://www.hunter.com/', chill-out,to_date('2020/03/29', 'YYYY/MM/DD'),to_date('2020/06/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (277,'https://blake-moore.com/', orchestra,to_date('2020/11/27', 'YYYY/MM/DD'),to_date('2021/02/12', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (278,'http://moses-carson.com/', latin jazz,to_date('2020/08/26', 'YYYY/MM/DD'),to_date('2020/11/21', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (279,'https://www.jimenez.com/', post-grunge,to_date('2021/02/14', 'YYYY/MM/DD'),to_date('2021/04/06', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (280,'https://www.johnson.com/', post-hardcore,to_date('2022/03/14', 'YYYY/MM/DD'),to_date('2022/04/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (281,'http://www.chambers.com/', dance-punk,to_date('2021/09/13', 'YYYY/MM/DD'),to_date('2021/10/27', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (282,'https://phelps.com/', grindcore,to_date('2021/06/14', 'YYYY/MM/DD'),to_date('2021/08/11', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (283,'http://butler-powers.net/', gangster rap,to_date('2021/06/04', 'YYYY/MM/DD'),to_date('2021/09/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (284,'https://www.williams.com/', blues-rock,to_date('2021/09/30', 'YYYY/MM/DD'),to_date('2021/11/12', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (285,'https://perkins.net/', british pop,to_date('2021/09/24', 'YYYY/MM/DD'),to_date('2021/11/21', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (286,'https://www.valentine.com/', rockabilly,to_date('2021/04/26', 'YYYY/MM/DD'),to_date('2021/07/24', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (287,'http://alvarez.com/', twee pop,to_date('2021/04/21', 'YYYY/MM/DD'),to_date('2021/06/13', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (288,'http://nguyen.com/', hard bop,to_date('2020/08/02', 'YYYY/MM/DD'),to_date('2020/08/16', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (289,'https://shaw.com/', chill-out,to_date('2021/02/24', 'YYYY/MM/DD'),to_date('2021/04/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (290,'https://www.knight.com/', broken beat,to_date('2021/03/17', 'YYYY/MM/DD'),to_date('2021/06/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (291,'https://lee-weber.net/', miami bass,to_date('2021/12/25', 'YYYY/MM/DD'),to_date('2022/03/26', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (292,'https://www.scott.net/', vocal,to_date('2022/02/08', 'YYYY/MM/DD'),to_date('2022/04/06', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (293,'https://hood.com/', post-grunge,to_date('2020/07/21', 'YYYY/MM/DD'),to_date('2020/08/23', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (294,'https://graves-baker.com/', brill building pop,to_date('2021/06/15', 'YYYY/MM/DD'),to_date('2021/08/11', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (295,'http://williams-lloyd.com/', funky house,to_date('2021/07/26', 'YYYY/MM/DD'),to_date('2021/10/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (296,'http://leonard.com/', flamenco,to_date('2022/02/27', 'YYYY/MM/DD'),to_date('2022/04/26', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (297,'https://lewis.com/', ballet,to_date('2020/03/15', 'YYYY/MM/DD'),to_date('2020/06/13', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (298,'https://www.rhodes-stevens.com/', country rock,to_date('2021/02/27', 'YYYY/MM/DD'),to_date('2021/03/18', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (299,'http://green.com/', brazilian pop music,to_date('2020/08/26', 'YYYY/MM/DD'),to_date('2020/10/05', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (300,'https://www.curry-powell.com/', doo-wop,to_date('2021/03/26', 'YYYY/MM/DD'),to_date('2021/06/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (301,'http://www.mcintyre.biz/', j pop,to_date('2021/06/06', 'YYYY/MM/DD'),to_date('2021/07/19', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (302,'https://green.com/', happy hardcore,to_date('2020/07/22', 'YYYY/MM/DD'),to_date('2020/10/30', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (303,'http://arnold-williams.com/', pop punk,to_date('2021/12/28', 'YYYY/MM/DD'),to_date('2022/01/15', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (304,'http://raymond-watson.org/', classic country,to_date('2021/10/27', 'YYYY/MM/DD'),to_date('2021/12/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (305,'http://www.murray.biz/', jazz,to_date('2021/08/04', 'YYYY/MM/DD'),to_date('2021/08/29', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (306,'http://foster.net/', chanson,to_date('2021/02/27', 'YYYY/MM/DD'),to_date('2021/03/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (307,'http://www.leon.info/', hip hop,to_date('2021/04/17', 'YYYY/MM/DD'),to_date('2021/05/18', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (308,'https://www.christensen.biz/', bel canto,to_date('2020/08/12', 'YYYY/MM/DD'),to_date('2020/10/02', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (309,'http://carson.net/', blues-rock,to_date('2020/09/26', 'YYYY/MM/DD'),to_date('2020/11/02', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (310,'http://www.sanders.com/', pop folk,to_date('2021/10/04', 'YYYY/MM/DD'),to_date('2021/11/02', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (311,'https://lewis-weeks.net/', british pop,to_date('2021/04/10', 'YYYY/MM/DD'),to_date('2021/04/27', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (312,'https://adams.com/', early music,to_date('2021/07/27', 'YYYY/MM/DD'),to_date('2021/10/19', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (313,'https://olson.biz/', musette,to_date('2020/03/04', 'YYYY/MM/DD'),to_date('2020/04/29', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (314,'http://www.morris-gutierrez.com/', downtempo,to_date('2021/05/20', 'YYYY/MM/DD'),to_date('2021/07/01', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (315,'https://andrews.com/', irish folk,to_date('2021/10/13', 'YYYY/MM/DD'),to_date('2021/12/23', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (316,'https://williams-elliott.com/', chill-out,to_date('2021/01/05', 'YYYY/MM/DD'),to_date('2021/02/02', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (317,'https://hernandez.net/', argentine rock,to_date('2020/03/26', 'YYYY/MM/DD'),to_date('2020/06/19', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (318,'https://russell-stevens.com/', country rock,to_date('2021/05/25', 'YYYY/MM/DD'),to_date('2021/08/25', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (319,'http://www.beltran.com/', cantonese pop,to_date('2020/10/29', 'YYYY/MM/DD'),to_date('2020/11/28', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (320,'http://www.mack-chavez.com/', hip hop,to_date('2020/10/30', 'YYYY/MM/DD'),to_date('2020/12/24', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (321,'https://hughes-washington.com/', teen pop,to_date('2020/10/15', 'YYYY/MM/DD'),to_date('2020/11/08', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (322,'https://martin-mata.com/', cabaret,to_date('2021/06/09', 'YYYY/MM/DD'),to_date('2021/07/30', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (323,'http://www.crosby-dennis.org/', instrumental pop,to_date('2021/02/16', 'YYYY/MM/DD'),to_date('2021/03/24', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (324,'http://www.anderson-baxter.com/', pop rock,to_date('2021/11/24', 'YYYY/MM/DD'),to_date('2022/02/05', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (325,'https://www.ferguson-nelson.com/', screamo,to_date('2021/10/11', 'YYYY/MM/DD'),to_date('2021/12/07', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (326,'http://www.choi.com/', jazz fusion,to_date('2021/08/13', 'YYYY/MM/DD'),to_date('2021/09/05', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (327,'https://hernandez.net/', progressive house,to_date('2020/10/12', 'YYYY/MM/DD'),to_date('2020/11/07', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (328,'http://www.ramos-cox.com/', jazz funk,to_date('2020/03/13', 'YYYY/MM/DD'),to_date('2020/06/06', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (329,'http://turner-golden.net/', cool jazz,to_date('2021/03/01', 'YYYY/MM/DD'),to_date('2021/06/05', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (330,'http://stein-williams.org/', ccm,to_date('2020/05/01', 'YYYY/MM/DD'),to_date('2020/06/21', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (331,'http://jenkins.info/', country rock,to_date('2022/03/07', 'YYYY/MM/DD'),to_date('2022/04/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (332,'https://www.horton.com/', flamenco,to_date('2020/01/23', 'YYYY/MM/DD'),to_date('2020/05/02', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (333,'http://www.harmon.net/', teen pop,to_date('2021/08/14', 'YYYY/MM/DD'),to_date('2021/11/17', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (334,'https://wright-evans.com/', bhangra,to_date('2021/10/16', 'YYYY/MM/DD'),to_date('2021/12/11', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (335,'http://downs.net/', breakbeat,to_date('2022/02/20', 'YYYY/MM/DD'),to_date('2022/03/05', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (336,'https://www.werner.com/', breakbeat,to_date('2020/06/04', 'YYYY/MM/DD'),to_date('2020/07/21', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (337,'https://www.larsen-king.biz/', heartland rock,to_date('2020/11/20', 'YYYY/MM/DD'),to_date('2021/01/21', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (338,'http://www.luna-stephens.com/', symphonic rock,to_date('2020/01/27', 'YYYY/MM/DD'),to_date('2020/04/12', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (339,'https://ellis-perkins.com/', latin jazz,to_date('2020/07/11', 'YYYY/MM/DD'),to_date('2020/09/15', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (340,'https://gordon.com/', tech house,to_date('2021/03/23', 'YYYY/MM/DD'),to_date('2021/05/28', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (341,'https://jones.com/', blues-rock,to_date('2021/02/18', 'YYYY/MM/DD'),to_date('2021/04/23', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (342,'https://www.mcbride.com/', turnablism,to_date('2020/01/12', 'YYYY/MM/DD'),to_date('2020/03/19', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (343,'https://christian-gonzalez.com/', club,to_date('2021/07/09', 'YYYY/MM/DD'),to_date('2021/08/15', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (344,'http://www.smith.info/', latin jazz,to_date('2020/06/06', 'YYYY/MM/DD'),to_date('2020/09/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (345,'https://www.shields.com/', chanson,to_date('2020/03/24', 'YYYY/MM/DD'),to_date('2020/05/09', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (346,'https://www.west.com/', instrumental rock,to_date('2021/12/20', 'YYYY/MM/DD'),to_date('2022/01/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (347,'http://www.marshall-miller.org/', ballad,to_date('2020/03/17', 'YYYY/MM/DD'),to_date('2020/05/15', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (348,'http://baird.com/', hip hop,to_date('2020/12/18', 'YYYY/MM/DD'),to_date('2021/03/03', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (349,'http://hebert.biz/', hip hop,to_date('2020/05/23', 'YYYY/MM/DD'),to_date('2020/06/05', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (350,'https://www.baker.net/', soundtrack,to_date('2021/07/09', 'YYYY/MM/DD'),to_date('2021/08/31', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (351,'https://www.frazier-salas.com/', nu metal,to_date('2021/12/12', 'YYYY/MM/DD'),to_date('2022/01/06', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (352,'http://www.brown-smith.com/', rock,to_date('2021/09/24', 'YYYY/MM/DD'),to_date('2021/10/11', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (353,'http://manning.com/', blues-rock,to_date('2021/10/18', 'YYYY/MM/DD'),to_date('2021/11/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (354,'https://lucero-walters.com/', stoner metal,to_date('2021/06/11', 'YYYY/MM/DD'),to_date('2021/07/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (355,'http://jensen-garcia.com/', vaudeville,to_date('2020/02/04', 'YYYY/MM/DD'),to_date('2020/02/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (356,'https://www.leon-parker.net/', blues-rock,to_date('2021/12/12', 'YYYY/MM/DD'),to_date('2022/02/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (357,'http://mccall-waller.com/', screamo,to_date('2022/01/25', 'YYYY/MM/DD'),to_date('2022/02/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (358,'https://www.johnson.org/', hip hop,to_date('2021/05/30', 'YYYY/MM/DD'),to_date('2021/06/10', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (359,'https://www.jackson-woodard.com/', chill-out,to_date('2020/10/31', 'YYYY/MM/DD'),to_date('2020/11/24', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (360,'https://www.clarke.biz/', brill building pop,to_date('2020/03/23', 'YYYY/MM/DD'),to_date('2020/06/19', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (361,'http://salazar.biz/', chanson,to_date('2021/08/25', 'YYYY/MM/DD'),to_date('2021/09/25', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (362,'https://www.reed.com/', post-hardcore,to_date('2022/04/01', 'YYYY/MM/DD'),to_date('2022/05/04', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (363,'http://johnson-allison.com/', disco,to_date('2020/05/04', 'YYYY/MM/DD'),to_date('2020/07/18', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (364,'http://www.johnson-martinez.info/', dark ambient,to_date('2020/04/22', 'YYYY/MM/DD'),to_date('2020/07/25', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (365,'http://wong.org/', cumbia,to_date('2022/03/09', 'YYYY/MM/DD'),to_date('2022/05/15', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (366,'http://www.lynch.com/', doom metal,to_date('2020/07/06', 'YYYY/MM/DD'),to_date('2020/09/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (367,'http://www.hunter-martin.com/', british pop,to_date('2020/11/14', 'YYYY/MM/DD'),to_date('2020/12/21', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (368,'http://www.stephenson-harris.com/', jazz fusion,to_date('2021/04/05', 'YYYY/MM/DD'),to_date('2021/05/28', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (369,'https://long.info/', cabaret,to_date('2022/03/03', 'YYYY/MM/DD'),to_date('2022/04/20', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (370,'http://smith.com/', male vocalist,to_date('2020/07/27', 'YYYY/MM/DD'),to_date('2020/09/28', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (371,'http://hall-lewis.org/', honky tonk,to_date('2020/10/07', 'YYYY/MM/DD'),to_date('2020/11/02', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (372,'https://www.hoover-moore.com/', pop punk,to_date('2020/01/25', 'YYYY/MM/DD'),to_date('2020/02/26', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (373,'https://smith-mcbride.com/', irish folk,to_date('2020/06/12', 'YYYY/MM/DD'),to_date('2020/08/15', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (374,'http://castro.com/', tango,to_date('2021/12/10', 'YYYY/MM/DD'),to_date('2022/03/03', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (375,'http://www.hurley.com/', vocal jazz,to_date('2020/07/07', 'YYYY/MM/DD'),to_date('2020/09/27', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (376,'https://www.pitts.com/', blues-rock,to_date('2021/10/31', 'YYYY/MM/DD'),to_date('2021/11/18', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (377,'http://contreras.com/', ccm,to_date('2021/11/14', 'YYYY/MM/DD'),to_date('2022/02/19', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (378,'https://www.mcdaniel.com/', hard house,to_date('2020/05/18', 'YYYY/MM/DD'),to_date('2020/07/25', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (379,'http://smith.com/', dance rock,to_date('2021/01/25', 'YYYY/MM/DD'),to_date('2021/03/30', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (380,'https://nelson-sutton.com/', technical death metal,to_date('2022/03/15', 'YYYY/MM/DD'),to_date('2022/04/02', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (381,'http://hawkins.com/', digital hardcore,to_date('2021/11/27', 'YYYY/MM/DD'),to_date('2022/01/03', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (382,'https://www.bautista-stokes.biz/', heavy metal,to_date('2020/12/24', 'YYYY/MM/DD'),to_date('2021/02/14', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (383,'http://moore-morris.com/', trip hop,to_date('2020/04/29', 'YYYY/MM/DD'),to_date('2020/08/03', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (384,'https://hernandez-chambers.biz/', blues-rock,to_date('2021/09/21', 'YYYY/MM/DD'),to_date('2021/10/01', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (385,'https://www.acosta-daniels.net/', indie rock,to_date('2021/09/23', 'YYYY/MM/DD'),to_date('2022/01/01', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (386,'http://harris-alvarado.com/', pop rap,to_date('2020/08/10', 'YYYY/MM/DD'),to_date('2020/09/19', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (387,'https://www.martin.com/', hip hop,to_date('2020/04/09', 'YYYY/MM/DD'),to_date('2020/05/26', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (388,'http://fleming-farley.com/', latin jazz,to_date('2021/11/25', 'YYYY/MM/DD'),to_date('2022/02/13', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (389,'https://reynolds.net/', gangster rap,to_date('2020/10/19', 'YYYY/MM/DD'),to_date('2020/12/19', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (390,'http://bryant.com/', smooth jazz,to_date('2021/06/14', 'YYYY/MM/DD'),to_date('2021/07/30', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (391,'https://www.jackson.com/', charanga,to_date('2021/03/21', 'YYYY/MM/DD'),to_date('2021/04/27', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (392,'https://johnson.com/', jazz fusion,to_date('2021/04/10', 'YYYY/MM/DD'),to_date('2021/06/25', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (393,'http://santiago.com/', tech house,to_date('2020/09/25', 'YYYY/MM/DD'),to_date('2020/12/31', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (394,'https://jones-murray.net/', celtic punk,to_date('2021/08/17', 'YYYY/MM/DD'),to_date('2021/09/28', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (395,'https://rodriguez.com/', power electronics,to_date('2020/04/18', 'YYYY/MM/DD'),to_date('2020/05/07', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (396,'http://thompson.com/', disco,to_date('2020/06/06', 'YYYY/MM/DD'),to_date('2020/08/22', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (397,'http://ray.com/', slack key guitar,to_date('2021/10/05', 'YYYY/MM/DD'),to_date('2021/10/31', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (398,'https://jones-gill.com/', melodic hardcore,to_date('2021/02/15', 'YYYY/MM/DD'),to_date('2021/04/02', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (399,'http://wright.com/', folk rock,to_date('2022/01/29', 'YYYY/MM/DD'),to_date('2022/04/01', 'YYYY/MM/DD'));
insert into SORIA.Exhibition (ExhibitionId, URL, Genre, StartTime, EndTime) values (400,'http://anderson-anderson.com/', Jewish music,to_date('2022/02/18', 'YYYY/MM/DD'),to_date('2022/03/19', 'YYYY/MM/DD'));
